
CC = g++
FLAGS = -std=c++11

all: Path_Test Graph_Test Dijkstra_Test

Path_Test: 
	$(CC) $(FLAGS) Path_Test.cpp -o Path_Test

Graph_Test:
	$(CC) $(FLAGS) Graph_Test.cpp -o Graph_Test

Dijkstra_Test:
	$(CC) $(FLAGS) Dijkstra_Test.cpp -o Dijkstra_Test
	
clean:
	rm -f *.o
	rm -f Path_Test Graph_Test Dijkstra_Test